### ISSUE TITLE
Extract bounding box from AHN2 sub-tiles (LAZ)

### ISSUE THREAD

**Issue by meiertgrootes** [eEcoLiDAR/AHN2_Kadaster#2]
Extract bounding box information for each AHN2 sub-tile. Output in format which can be imported to PostGIS.

- [x] Get test files 

- [x] Install LAS Tools and PDAL

- [x] Install python-pdal

- [x] Do ground and unclassified tiles exist for each sub-tile index? to be checked.

- [x] Check location and format of bounding box for a sub-tile from documentation 

- [x] Set up postgis DB locally

- [x] install pylas

- [x] Reading the bounding box of a tile using pylas

- [x] Export bounding boxes as a polygons into a csv file.

- [x] Write short in-code documentation 

- [x] Export BBoxes in separate CSV files corresponding the the 'super' (Kadaster) tiles

**Comment by elboyran** [comment]
The bounding box of a (sub)tile is contained in the Public Header Block. The format of the block is described in Table 3 from the [LAS14 format document](https://www.asprs.org/wp-content/uploads/2010/12/LAS_1_4_r13.pdf). The relevant fields seem to be Max/Min X/Y/Z.

**Comment by meiertgrootes** [comment]
Are these fields the bounding box extent, or are they the min/max values corresponding to the points in the file. Having a brief look, it seems to be the latter, although I'm not sure. using the pdal info <filename> option seems to list both these parameters and an additional bounding box, with the latter in 2d

**Comment by elboyran** [comment]
LAS Tools is Windows only!

**Comment by meiertgrootes** [comment]
not entirely there is source that can be built under linux
rapidlasso.com is the current website, from which LAStools is distributed

**Comment by elboyran** [comment]
It looks like both the ground and unclassified tiles exist for each sub-tile index (at least for the test subset).

**Comment by meiertgrootes** [comment]
> * [x]  Reading the bounding box of a tile using laspy

Is this now pylas ?

**Comment by elboyran** [comment]
Yes. Fixed.
